# Generated by Django 2.1.3 on 2018-12-18 23:03

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181218_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326),
        ),
    ]
